"""add category tags intents to knowledge_chunk

Revision ID: 387d6b524737
Revises: fdfcaf5c597d
Create Date: 2026-08-18 18:13:50.703102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387d6b524737'
down_revision: Union[str, Sequence[str], None] = 'fdfcaf5c597d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunk', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('knowledge_chunk', sa.Column('tags', sa.String(length=500), nullable=True))
    op.add_column('knowledge_chunk', sa.Column('intents', sa.String(length=300), nullable=True))
    op.alter_column('knowledge_chunk', 'external_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_index(op.f('ix_knowledge_chunk_embedding_hnsw'), table_name='knowledge_chunk', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(
        'ix_knowledge_chunk_embedding_hnsw',
        'knowledge_chunk',
        ['embedding'],
        unique=False,
        postgresql_using='hnsw',
        postgresql_ops={'embedding': 'vector_cosine_ops'},
    )
    op.drop_constraint(op.f('uq_knowledge_chunk_external_id'), 'knowledge_chunk', type_='unique')
    op.create_index(op.f('ix_knowledge_chunk_category'), 'knowledge_chunk', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_chunk_external_id'), 'knowledge_chunk', ['external_id'], unique=True)
    op.alter_column('knowledge_document', 'external_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(op.f('uq_knowledge_document_external_id'), 'knowledge_document', type_='unique')
    op.create_index(op.f('ix_knowledge_document_external_id'), 'knowledge_document', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_document_external_id'), table_name='knowledge_document')
    op.create_unique_constraint(op.f('uq_knowledge_document_external_id'), 'knowledge_document', ['external_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('knowledge_document', 'external_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_knowledge_chunk_external_id'), table_name='knowledge_chunk')
    op.drop_index(op.f('ix_knowledge_chunk_category'), table_name='knowledge_chunk')
    op.create_unique_constraint(op.f('uq_knowledge_chunk_external_id'), 'knowledge_chunk', ['external_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_knowledge_chunk_embedding_hnsw'), 'knowledge_chunk', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('knowledge_chunk', 'external_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('knowledge_chunk', 'intents')
    op.drop_column('knowledge_chunk', 'tags')
    op.drop_column('knowledge_chunk', 'category')
    # ### end Alembic commands ###
