"""add session_token, source_page, status, last_activity_at to chat_session; add intent to chat_message

Revision ID: abca303d80d4
Revises: 387d6b524737
Create Date: 2026-08-20 15:32:23.161873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abca303d80d4'
down_revision: Union[str, Sequence[str], None] = '387d6b524737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunk_embedding_hnsw'), table_name='knowledge_chunk', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_knowledge_chunk_embedding_hnsw'), 'knowledge_chunk', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
