"""add session_token, source_page, status, last_activity_at to chat_session; add intent to chat_message

Revision ID: acfa9bc063a4
Revises: abca303d80d4
Create Date: 2026-08-20 16:22:40.952677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acfa9bc063a4'
down_revision: Union[str, Sequence[str], None] = 'abca303d80d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('intent', sa.String(length=50), nullable=True))
    op.add_column('chat_session', sa.Column('session_token', sa.Uuid(), nullable=False))
    op.add_column('chat_session', sa.Column('source_page', sa.String(length=500), nullable=True))
    op.add_column('chat_session', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('chat_session', sa.Column('last_activity_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_chat_session_session_token'), 'chat_session', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_session_session_token'), table_name='chat_session')
    op.drop_column('chat_session', 'last_activity_at')
    op.drop_column('chat_session', 'status')
    op.drop_column('chat_session', 'source_page')
    op.drop_column('chat_session', 'session_token')
    op.drop_column('chat_message', 'intent')
    # ### end Alembic commands ###
