"""make lead_submission name/email nullable, add status column

Revision ID: b941fc16efe7
Revises: acfa9bc063a4
Create Date: 2026-08-20 19:13:26.093119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b941fc16efe7'
down_revision: Union[str, Sequence[str], None] = 'acfa9bc063a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_submission', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('lead_submission', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('lead_submission', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead_submission', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('lead_submission', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('lead_submission', 'status')
    # ### end Alembic commands ###
